name: BeginnerCode
version: '${project.version}'
main: me.cynshiii.beginnercode.BeginnerCode
api-version: 1.19
authors: [ Cynshiii ]
description: All of my BeginnerCode in one place.
commands:
  feed:
    description: Satiate your hunger
    usage: /<command>
    aliases:
      - eat
      - hungry
      - cynateit
  fly:
    description: Enable creative flight
    usage: /<command>
    aliases:
      - flight
      - pleasehelpcynthrewmethousandsofblocksintheairandimfallingatthespeedofsound
  heal:
    description: Heal your woulds
    usage: /<command>
    aliases:
      - bandage
      - cure
      - cynbrokemybonespleasehealme
  god:
    description: Become invulnerable
    usage: /<command>
    aliases:
      - invincibility
      - cantdie
      - cynistoogoodatthegame
  itemname:
    description: Rename the item in your hand
    usage: /<command> <args>_<args>
    aliases:
      - rename
      - changename
      - cynatetheoriginalnamesoineedanewone
  biome:
    description: See the name of the biome you are currently in
    usage: /<command>
    aliases:
      - biometype
      - getbiome
      - whatbiomeiscynmakingafarminthistime
  plantable:
    description: See if you can plant crops on the block you're standing on
    usage: /<command>
    aliases:
      - caniplanthere
      - croplight
      - cancynmakeafarmhere
  repeat:
    description: Have the words you say in your command repeat back to you
    usage: /<command> <args>
  wordsofencouragement:
    description: Get some words of encouragement
    usage: /<command>
    aliases:
      - woe
      - encouragement
      - cynneedsemotionalsupport
  spawn:
    description: Teleport to the server's spawnpoint
    usage: /<command>
  setspawn:
    description: Set the server's spawnpoint
    usage: /<command>